services:

  postgres:
    image: postgres:16-alpine
    container_name: locker_delivery_postgres
    environment:
      POSTGRES_DB: locker_delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - locker_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d locker_delivery"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: locker_delivery_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lockerdelivery.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "9000:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - locker_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  locker_network:
    driver: bridge
